[plugins]
blossom = { id = "net.kyori.blossom", version = "2.1.0" }
localization = { id = "ca.stellardrift.localization", version = "6.1.0" }
runPaper = { id = "xyz.jpenilla.run-paper", version = "2.3.1" }
sponge-gradle = { id = "org.spongepowered.gradle.plugin", version = "2.3.0" }

[versions]
adventure = "4.18.0"
adventurePagination = "4.0.0-SNAPSHOT"
adventurePlatform = "4.3.4"
cloud = "2.0.0"
cloudMinecraft = "2.0.0-beta.10"
cloudModded = "2.0.0-beta.10"
cloudSponge = "2.0.0-SNAPSHOT"
configurate = "4.1.2"
typesafeConfig = "1.4.3"
checkerQual = "3.48.4"
slf4j = "1.7.32"
log4jSlf4jImpl = "2.8.1"
gson = "2.8.0"
guava = "21.0"
bstats = "3.1.0"
paperApi = "1.16.5-R0.1-SNAPSHOT"
paperLib = "1.0.8"
fabricApi = "0.114.0+1.21.4"
fabricLoader = "0.16.9"
minecraft = "1.21.4"
adventurePlatformMod = "6.2.0"
mixin = "0.8.7"
neoforge = "21.4.47-beta"
neoForm = "1.21.4-20241203.161809"

# buildSrc
indra = "3.1.3"
shadow = "8.3.6"
mod-publish-plugin = "0.8.4"
hangarPublishPlugin = "0.1.2"

[libraries]
adventureBom = { group = "net.kyori", name = "adventure-bom", version.ref = "adventure" }
adventureApi = { group = "net.kyori", name = "adventure-api" }
adventureTextSerializerLegacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventureSerializerConfigurate4 = { group = "net.kyori", name = "adventure-serializer-configurate4", version.ref = "adventure" }
adventureTextFeaturePagination = { group = "net.kyori", name = "adventure-text-feature-pagination", version.ref = "adventurePagination" }
adventurePlatformBukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventurePlatform" }
adventurePlatformFabric = { group = "net.kyori", name = "adventure-platform-fabric", version.ref = "adventurePlatformMod" }
adventurePlatformNeoforge = { group = "net.kyori", name = "adventure-platform-neoforge", version.ref = "adventurePlatformMod" }
minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }

cloudBom = { group = "org.incendo", name = "cloud-bom", version.ref = "cloud" }
cloudMinecraftBom = { module = "org.incendo:cloud-minecraft-bom", version.ref = "cloudMinecraft" }
cloudCore = { group = "org.incendo", name = "cloud-core" }
cloudMinecraftExtras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloudMinecraft" }
cloudPaper = { group = "org.incendo", name = "cloud-paper" }
cloudSponge = { group = "org.incendo", name = "cloud-sponge", version.ref = "cloudSponge" }
cloudFabric = { group = "org.incendo", name = "cloud-fabric", version.ref = "cloudModded" }
cloudNeoforge = { group = "org.incendo", name = "cloud-neoforge", version.ref = "cloudModded" }

mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }

configurateCore = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
configurateHocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
typesafeConfig = { group = "com.typesafe", name = "config", version.ref = "typesafeConfig" }

checkerQual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerQual" }

slf4jApi = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4jJdk14 = { group = "org.slf4j", name = "slf4j-jdk14", version.ref = "slf4j" }
log4jSlf4jImpl = { group = "org.apache.logging.log4j", name = "log4j-slf4j-impl", version.ref = "log4jSlf4jImpl" }

legacyPluginBase = { group = "xyz.jpenilla", name = "legacy-plugin-base", version = "0.0.1+128-SNAPSHOT" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

bstatsBukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }

paperApi = { group = "com.destroystokyo.paper", name = "paper-api", version.ref = "paperApi" }
paperLib = { group = "io.papermc", name = "paperlib", version.ref = "paperLib" }

fabricApi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabricApi" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabricPermissionsApi = "me.lucko:fabric-permissions-api:0.3.3"
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

zNeoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

# buildSrc
build-indraCommon = { group = "net.kyori", name = "indra-common", version.ref = "indra" }
build-indraLicenser = { group = "net.kyori", name = "indra-licenser-spotless", version.ref = "indra" }
build-shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
build-mod-publish-plugin = { module = "me.modmuss50:mod-publish-plugin", version.ref = "mod-publish-plugin" }
build-hangarPublishPlugin = { group = "io.papermc", name = "hangar-publish-plugin", version.ref = "hangarPublishPlugin" }

[bundles]
configurate = ["configurateCore", "configurateHocon", "typesafeConfig"]
